/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}

rootProject.name = "LifeNewPvE"
include("api")
include("core")
include("minecraft")
include("common")
