name: LifeNewPvE
version: '1.1.0'
main: net.azisaba.lifenewpve.LifeNewPvE
api-version: '1.21'

depend:
  - MythicMobs
  - Multiverse-Core
  - WorldGuard

commands:
  worldregen:
    permission: lifenewpve.command.worldregen
    aliases:
      - wr
      - worldRegen
  worldcreate:
    permission: lifenewpve.command.worldcreate
    aliases:
      - wc
      - worldCreate
  worldteleport:
    permission: lifenewpve.command.worldteleport
    aliases:
      - wt
      - worldTeleport
      - wsp
      - ws
  worldset:
    permission: lifenewpve.command.worldset
    aliases:
      - wset
      - wse
      - wst
  spawn:
    permission: lifenewpve.command.spawn
    aliases:
      - sp
  setspawn:
    permission: lifenewpve.command.setspawn
    aliases:
      - ss
      - setSpawn
  savepoint:
    permission: lifenewpve.command.savepoint
    aliases:
      - spoint
      - spo
      - saves
  mode:
    permission: lifenewpve.command.mode
    aliases:
      - md

permissions:
  lifenewpve.reload.mythicmobs:
    default: op
    description: mythicmobsをリロードしたことを伝えるために使用する権限
